#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "beszel-agent"
name = "Beszel Agent"
description.en = "Agent for the Beszel server monitor"
description.fr = "Agent pour le monitoring de serveurs Beszel"

version = "0.19.0~ynh1"

maintainers = ["tituspijean"]

[upstream]
license = "MIT"
website = "https://www.beszel.dev/"
admindoc = "https://beszel.dev/guide/agent-installation"
code = "https://github.com/henrygd/beszel"

[integration]
yunohost = ">= 12.1.39"
helpers_version = "2.1"
architectures = [ "amd64", "arm64", "armhf" ]
multi_instance = true

ldap = "not_relevant"
sso = "not_relevant"

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.alert]
    type = "alert"
    style = "info"
    icon = "info-circle"
    ask.en = "This app needs to be linked to an already-installed Beszel application. In Beszel's home page, click on `+ Add System`, then fill in this form with the Public Key and Token from the Binary tab. After installation, change the Port with the reported value."
    ask.fr = "Cette application a besoin d'être liée à une installation existante de l'app Beszel. Dans la page principale de Beszel, cliquez sur `+ Ajouter Système`, et remplissez ce formulaire avec la Clé publique et le Token de l'onglet Binaire. Après l'installation, modifiez le Port avec la valeur rapportée."

    [install.public_key]
    type = "string"
    ask.en = "Beszel server's public key"
    ask.fr = "Clé publique du serveur Beszel"

    [install.token]
    type = "password"
    ask.en = "Beszel server token"
    ask.fr = "Jeton (token) du serveur Beszel"

    [install.hub_url]
    type = "string"
    ask.en = "Beszel server's URL"
    ask.fr = "URL du serveur Beszel"
    pattern.regexp = "^https?://"
    pattern.error.en = "The URL should start with https:// (or unsafely http://)."
    pattern.error.fr = "L'URL devrait commencer par https:// (ou de manière peu sûre http://)."

[resources]

    [resources.sources]

    [resources.sources.main]
    in_subdir = false
    amd64.url = "https://github.com/henrygd/beszel/releases/download/v0.19.0/beszel-agent_linux_amd64.tar.gz"
    amd64.sha256 = "0f85891b290146b336f5c813d1e535e992da35ee79de876e920e2ec748ab732c"
    arm64.url = "https://github.com/henrygd/beszel/releases/download/v0.19.0/beszel-agent_linux_arm64.tar.gz"
    arm64.sha256 = "3a0b0c471506a02d8de79d03f7a45132b54010adc105c6208ffe8b8aedc1da38"
    armhf.url = "https://github.com/henrygd/beszel/releases/download/v0.19.0/beszel-agent_linux_arm.tar.gz"
    armhf.sha256 = "e70086a77effb44a6b142da9e6761c8fe8bd13546ca4fd1940bd15e3baf44661"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "beszel-agent_linux_amd64.tar.gz"
    autoupdate.asset.arm64 = "beszel-agent_linux_arm64.tar.gz"
    autoupdate.asset.armhf = "beszel-agent_linux_arm.tar.gz"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.ports]

    [resources.apt]
    packages = ["smartmontools"]
