#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    args.public_key = "ssh-ed25519 ThisIsSomePublicKey"
    args.token = "ThisIsSomeToken"
    args.hub_url = "https://beszel-server.test"
